name: build

on:
  push:
    branches:
      - master
      - develop
    paths-ignore:
      - '**.md'
    tags:
      - 'v*'
  pull_request:
    branches:
      - master
      - develop
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest

    name: Build

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/determinate-nix-action@v3

      - name: Build all checks and outputs
        run: |
          nix develop ./dev -c om ci
          cd dev
          nix develop -c om ci

      - name: Build plugin zip
        run: |
          nix build .#wp2static
          cp result/wp2static.zip plugin.zip

      - name: Upload plugin as artifact
        uses: actions/upload-artifact@v4
        with:
          name: plugin
          path: plugin.zip

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          files: plugin.zip
