name: codequality

on:
  push:
    branches:
    - master
    - develop
  pull_request:
    branches:
    - master
    - develop
jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
  test:
    runs-on: ubuntu-latest

    name: PHP tests and coding standards

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Cache PHP dependencies
      uses: actions/cache@v4
      with:
        path: vendor
        key: ${{ runner.OS }}-build-${{ hashFiles('**/composer.lock') }}

    - name: Validate Composer setup
      run: composer validate --strict

    - name: Install PHP dependencies
      run: composer install --no-interaction

    - name: Run parallel lint
      run: composer run-script lint

    - name: Test PHP Coding Standards
      run: composer run-script phpcs

    - name: Test code against PHP 8.1 standard
      run: composer run-script php81

    - name: Test code against PHP 8.2 standard
      run: composer run-script php82

    - name: Test code against PHP 8.3 standard
      run: composer run-script php83

    - name: Test code against PHP 8.4 standard
      run: composer run-script php84

    - name: Run PHPStan static analyser
      run: composer run-script phpstan

    - name: Run unit tests, ignoring external requests
      run: composer run-script phpunit -- --exclude-group ExternalRequests

